env: "local"

http_server:
  address: "localhost:8099"
  timeout: 5s
  idle_timeout: 60s
storage:
  user: "postgres"
  dbname: "distributed_calculator"
  password: "password"
  host: "localhost"
  post: "5432"
  sslmode: "disable"
  url: "postgres://postgres:password@postgres:5432/distributed_calculator?sslmode=disable"

operation:
  count_operation: 4
  addition: 0
  subtraction: 0
  multiplication: 0
  division: 0

quick_access_storage:
  addr: "redis:6379"
  ttl: 360s
  password: ""
  db: 0