version: '3.8'

services:
  postgres:
    container_name: daec_postgresql
    image: postgres
    ports:
      - "8100:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: distributed_calculator

    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: daec_rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"
    restart: always
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  redis:
    container_name: daec_redis
    image: redis:latest
    ports:
      - '8101:6379'

  orchestrator:
    restart: unless-stopped
    container_name: daec_orchestrator
    image: orchestrator:latest
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    ports:
      - '8099:8099'
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/distributed_calculator?sslmode=disable
      REDIS_URL: redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

volumes:
  pgdata:
  rabbitmqdata: