version: '3.8'

services:
  postgres:
    container_name: daec_postgresql
    image: postgres
    ports:
      - "8100:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: distributed_calculator
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: daec_redis
    image: redis:latest
    ports:
      - '8101:6379'
    networks:
      - app_network

  orchestrator:
    restart: unless-stopped
    container_name: daec_orchestrator
    image: orchestrator:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    network_mode: host


volumes:
  pgdata:

networks:
  app_network:
    driver: bridge