# config/config.yaml

env: "local"

http_server:
  address: "localhost:8099"
  timeout: 5s
  idle_timeout: 60s
storage:
  user: "postgres"
  dbname: "distributed_calculator"
  password: "password"
  host: "localhost"
  post: "5432"
  sslmode: "disable"

operation:
  count_operation: 4
  addition: 0
  subtraction: 0
  multiplication: 0
  division: 0