env: "local"

auth_service:
  grpc_port: 8103
  token_ttl: 1h

storage:
  user: "postgres"
  dbname: "distributed_calculator"
  password: "password"
  host: "localhost"
  port: "8100"
  sslmode: "disable"
