env: "local"

auth_service:
  grpc_port: 8102
  cost: 12
  secret: "bdd60f0540254782d896196e129b2610c2b574d1055a6517712ed0b9073e46f1"
  token_ttl: 1h
  check_required_secret: true

storage:
  user: "postgres"
  dbname: "distributed_calculator"
  password: "password"
  host: "localhost"
  port: "8100"
  sslmode: "disable"
