env: "local"

storage:
  user: "postgres"
  dbname: "distributed_calculator"
  password: "password"
  host: "localhost"
  port: "8100"
  sslmode: "disable"

operation:
  count_operation: 4
  addition: 0
  subtraction: 0
  multiplication: 0
  division: 0
  permission_to_seed: true

agent:
  count_calculator: 4

expression_solver:
  grpc_port: 8103
