openapi: 3.0.0
info:
  title: Distributed Arithmetic Expression Calculator
  version: 1.0.0
servers:
  - url: http://localhost:8099
paths:
  /sign_up:
    post:
      operationId: sign_up
      description: Sign up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        200:
          description: Success
        401:
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /login:
    post:
      operationId: login
      description: Login to get JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTToken'
        403:
          description: Invalid credentials
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /expressions:
    post:
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: X-Idempotency-Token
          schema:
            type: string
      summary: Submit an arithmetic expression
      operationId: submitExpression
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputExpression'
        required: true
      responses:
        200:
          description: Expression accepted and processing started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdRespond'
        400:
          description: Invalid expression
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        401:
          description: Unauthorized
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
    get:
      security:
        - bearerAuth: []
      summary: Get expressions
      responses:
        200:
          description: Got expression
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Expression'
        401:
          description: Unauthorized
        404:
          description: No expressions
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /expressions/{id}:
    get:
      security:
        - bearerAuth: []
      summary: Get expression
      operationId: getExpression
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Got expression
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Expression'

        400:
          description: Invalid id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        401:
          description: Unauthorized
        403:
          description: Permission denied
        404:
          description: Expression not found
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /operations:
    get:
      security:
        - bearerAuth: []
      summary: List operations
      operationId: listOperations
      responses:
        200:
          description: List of operations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Operation'
        400:
          description: Invalid operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        401:
          description: Unauthorized
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

    put:
      security:
        - bearerAuth: []
      summary: Update operation execution time
      operationId: updateOperationTime
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operation'
        required: true
      responses:
        200:
          description: Update duration (in seconds) of operation
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Operation'
        400:
          description: Invalid operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
        401:
          description: Unauthorized
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'

  /mini_calculators:
    get:
      security:
        - bearerAuth: []
      summary: List computational capabilities
      operationId: listComputationalCapabilities
      responses:
        200:
          description: List of computational capabilities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MiniCalculator'
        401:
          description: Unauthorized

components:
  schemas:
    Expression:
      type: object
      properties:
        id:
          type: integer
        expression:
          type: string
        answer:
          type: string
        status:
          type: string
          enum: [completed, in process, invalid]
        createdAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true
        userId:
          type: integer
          format: int64
      required:
        - id
        - expression
        - answer
        - status
        - createdAt
        - completedAt
        - userId

    InputExpression:
      type: object
      properties:
        expression:
          type: string
      required:
        - expression

    Operation:
      type: object
      properties:
        operationKind:
          type: string
          enum: ["addition", "subtraction", "multiplication", "division"]
        durationInSecond:
          type: integer
      required:
        - operationKind
        - durationInSecond

    MiniCalculator:
      type: object
      properties:
        resourceId:
          type: integer
        leastExpression:
          $ref: '#/components/schemas/LeastExpression'
      required:
        - resourceId
        - leastExpression

    LeastExpression:
      type: object
      properties:
        number1:
          type: number
        number2:
          type: number
        operation:
          type: string
          enum: ["addition", "subtraction", "multiplication", "division"]
        idExpression:
          type: integer
      required:
        - number1
        - number2
        - operation
        - idExpression

    APIError:
      type: object
      properties:
        description:
          type: string
      required:
        - description

    IdRespond:
      type: object
      properties:
        id:
          type: integer
      required:
        - id

    UserCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    JWTToken:
      type: object
      properties:
        token:
          type: string
      required:
        - token
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []